---
output:
  bookdown::word_document2:
    reference_docx: Template.docx
    fig_caption: yes
    toc: no
    number_sections: no
    df_print: kable
editor_options: 
  chunk_output_type: inline
bibliography: references.bib
link-citations: true
urlcolor: blue
linkcolor: blue
citationcolor: blue
csl: "`r here:::here('citationstyle.csl')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
	message = FALSE,
	warning = FALSE,
	progress = FALSE,
	cache = FALSE,
	dpi = 300
)

set.seed(513)
options(repos = c(CRAN = "http://cran.rstudio.com"))
options(timeout=60*30) #timeout downloads that last longer than 30 minutes

if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  devtools,
  knitr, # markdown documents
  flextable, # plot tables
  bookdown, # figure numbering in markdown
  here, # easy file structure
  tidyverse, # data manipulation
  ggplot2, # figures
  patchwork, # multiple figures
  grid, # multiple figures
  gridExtra,
  ggsci, # color palettes
  colorspace, # color palettes
  RColorBrewer, # color palettes
  ggcorrplot, # plot correlation between variables
  sf, # spatial data (new pkg)
  terra, # raster data
  raster, # (old pkg)
  rasterVis,
  tidyterra, #tidyverse extension to spatial data
  tmap, # easy plotting of maps
  terrainr, # elevation data
  spatialEco, # hli, tpi
  readxl, # read in excel data
  parallel,
  doParallel, 
  FNN,
  rgeos,
  elevatr, 
  tidymodels,
  vip,
  DALEXtra,
  ncf, #spline correlog
  probably, 
  spatialsample, # spatial sampling
  spatialRF
) 
terraOptions(progress=0) # suppress all progress bars in terra
cores <- parallel::detectCores() # Set number of cores for parallel processing

# Set custom plotting theme
theme_new <- function(base_size = 9,base_family = "Helvetica"){
  theme_classic(base_size = base_size, base_family = base_family) %+replace%
    theme(
      axis.line.x = element_line(color="black", linewidth = 0.25),
      axis.line.y = element_line(color="black", linewidth = 0.25),
      axis.title = element_text(size = 9),
      axis.text = element_text(colour="black", size=8),
      legend.key=element_rect(colour=NA, fill =NA),
      panel.grid = element_blank(),   
      plot.background = element_rect(fill = NA, colour = NA),
      panel.border = element_rect(fill = NA, colour = NA),
      panel.background = element_rect(fill = "white", colour = "black"), 
      strip.background = element_rect(fill = "white"),
      strip.text = element_text(size = 9)
      
    )
}
theme_set(theme_new())

set_flextable_defaults(
  font.family="Times", 
  font.size=12,
  line_spacing=1,
  padding.bottom=1,
  padding.top=1,
  text.align='center')

# Set directory structure for project
dir.create(here("Data"), showWarnings = FALSE)
dir.create(here("Data", "Spatial"), showWarnings = FALSE)
dir.create(here("Results"), showWarnings = FALSE)
dir.create(here("Results", "Figures"), showWarnings = FALSE)
```

# Title

Climate-driven decreases in aspen's distribution and opportunities for future expansion across the Southern Rocky Mountains

# Running Title

Climate change and aspen's distribution

# Authors

[Sarah J. Hart](https://orcid.org/0000-0001-8371-8568)^a,1^, [Asha Paudel](https://orcid.org/0000-0002-5663-0218)^a^, and [Maxwell C. Cook](https://orcid.org/0000-0003-4865-5025)^b,c^

# Affiliations

a - Department of Forest and Rangeland Stewardship, Colorado State University, Fort Collins, CO 80523, USA

b - Department of Geography, University of Colorado Boulder, Boulder, CO 80309, USA

c - Earth Lab, Cooperative Institute for Research in Environmental Sciences (CIRES), University of Colorado Boulder, Boulder, CO 80309, USA

1 - corresponding author; email address: Sarah.Hart\@colostate.edu

# Funding information

This research was funded by the Joint Fire Science Program (JFSP, Project ID 21-2-02-29).

# Acknowledgements

The Southern Rocky Mountains are the sacred homelands to many Indigenous nations – we honor their past, present, and future generations, who have lived here and stewarded these forests for millennia.

# Author contributions: CRediT

**Sarah J. Hart:** Conceptualization, Funding acquisition, Methodology, Formal analysis, Writing- Original draft preparation, Writing – review and editing; **Asha Paudel**: Writing – review and editing, Methodology. **Maxwell C. Cook**: Funding acquisition, Writing – review and editing;

# Data availability

Code and maps of the predicted habitat suitability area available through Dryad via the following anonymized link: [http://datadryad.org/stash/share/gGubdiD6hCORznmbeHB6gkWoxodyj25Soa3s3yfOfHg](https://nam10.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdatadryad.org%2Fstash%2Fshare%2FgGubdiD6hCORznmbeHB6gkWoxodyj25Soa3s3yfOfHg&data=05%7C02%7Csarah.hart%40colostate.edu%7Cc00ff4ef23d4486ecd8e08dceee39cf4%7Cafb58802ff7a4bb1ab21367ff2ecfc8b%7C0%7C0%7C638647908580903395%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=i%2B45VPN9dbfLKYiR0rbKPxa%2BoWV6Kc%2BHP8v%2FlumACRM%3D&reserved=0).
